name: okru_oauth
description: okru auth library
version: 1.0.1
repository: "https://github.com/Olifemus/okru_oauth"

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.eegorov.okru_oauth
        pluginClass: OkruOauthPlugin
      ios:
        pluginClass: OkruOauthPlugin
